[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "ollama>=0.1.6",
    "uvicorn>=0.27.0",
    "python-multipart>=0.0.9", # Required for file uploads
]
