[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "ollama>=0.4.5",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.0",
]
